### ISSUE TITLE
AssertionFailedError on removing user

### ISSUE THREAD

**Issue by holm** [ruimarinho/authy-client#38]
At https://github.com/seegno/authy-client/blob/master/src/client.js#L144 there is an asserting on the exact message from Authy on user removal. It seems Authy have changed the message to be `User removed from application` now. 

I don't think it makes sense to assert on responses at this level. You would not expect the exact message in a result to be fixed and never change.

**Comment by josh-authy** [comment]
Agreed.  This validation seems a bit excessive.

**Comment by ruimarinho** [comment]
Hi guys, sorry for the delay here. The reason behind this check - which I agree it might seem overly zealous at first - was that sometime during Authy's API lifecycle, we often received a status 200 where the only error was actually the message being different.

Now, I don't think this is the case anymore, so removing those checks seems fine to me. @holm or @josh-authy - would you like to contribute with a PR for that?

**Comment by ruimarinho** [comment]
@holm if you want to push changes for this as well, feel free to submit multiple PRs!
