### ISSUE TITLE
Possible to copy 2fa token to clipboard?

### ISSUE THREAD

**Issue by nitrocode** [ruimarinho/authy-client#48]
I use the lastpass cli to copy creds to my clipboard. Is it possible to do with the authy api or this authy client? If not, is this a viable feature request? :smile:

**Comment by ruimarinho** [comment]
I don't see how this could be a feature of authy-client, sorry :)

**Comment by merchako** [comment]
The Authy workflow for Alfred can add the 2FA tokens to your clipboard: https://github.com/momaek/authy
