### ISSUE TITLE
"deleteUser" POSTing to wrong endpoint

### ISSUE THREAD

**Issue by camlegleiter** [ruimarinho/authy-client#50]
The `deleteUser` API call is not hitting the correct endpoint as of the current version.

[Authy API Docs](https://www.twilio.com/docs/authy/api/users#remove-a-user): `/protected/{FORMAT}/users/{USER ID}/remove`
[authy-client `deleteUser` call](https://github.com/ruimarinho/authy-client/blob/master/src/client.js#L138): `/protected/json/users/{USER ID}/delete`

The `authy-client` needs to hit "remove" instead of "delete" for users (see the last component in the URIs above). Otherwise this results in a 404 call.

**Comment by ruimarinho** [comment]
Interesting. Authy being Authy 🤷‍♂️

**Comment by ruimarinho** [comment]
Fixed, thanks.
