### ISSUE TITLE
Reference to all optional arguments

### ISSUE THREAD

**Issue by eorroe** [ruimarinho/authy-client#51]
Sorry but I can't seem to find where are the options I can pass to `startPhoneVerification` I want to change the `code_length`

A reference to where I can easily know what options to pass for each function would be of great use.

I'm using https://www.twilio.com/docs/verify/api/verification but the parameters don't match.

For example this library uses `phone` instead of `phone_number` so any reference to the right way to pass options would be great, the **README** doesn't show all options that can be passed

**Comment by davvilla** [comment]
From looking at https://github.com/ruimarinho/authy-client/blob/master/src/client.js it doesn't seem like it's an option to pass in at the moment.

As a side note tor future readers, the locale parameter needs to be passed as a separate object:

```
await this.authyClient.startPhoneVerification({
        countryCode,
        phone,
        via: enums.verificationVia.SMS
      }, {
        locale: enums.locale.SPANISH
      })
```

**Comment by var** [comment]
I gave a pull request for code length in #54

**Comment by ruimarinho** [comment]
This is now supported @eorroe.
