### ISSUE TITLE
Use proxy

### ISSUE THREAD

**Issue by sm2017** [ruimarinho/authy-client#55]
How can I set a http or socks proxy?

**Comment by sm2017** [comment]
@ruimarinho reply please

**Comment by sm2017** [comment]
@ruimarinho Still waiting for your reply

**Comment by ruimarinho** [comment]
@sm2017 you could try setting the env variables `HTTP_PROXY` / `HTTPS_PROXY` as the `request` module should honor them. Your mileage may vary as I haven't tested this.
