### ISSUE TITLE
Trying to use it on react with webpack but installing it gave me all these missing module errors

### ISSUE THREAD

**Issue by scottyh527** [ruimarinho/authy-client#57]
I'm currently using react with webpack, I'm trying to incorporate authy for 2fa but upon installing this package it said I'm missing all these packages I had never heard of, is this normal? Do i need to install each one that they say are missing? 

ERROR in ./node_modules/authy-client/dist/src/client.js
Module not found: Error: Can't resolve '../package' in '/Users/scotth527/Desktop/UC Director Front end/UC-Director/UC-Director/node_modules/authy-client/dist/src'
 @ ./node_modules/authy-client/dist/src/client.js 30:15-36
 @ ./node_modules/authy-client/dist/src/index.js
 @ ./src/views/Pages/Login/Login.js
 @ ./src/App.js
 @ ./src/index.js
 @ multi ./src/index.js

ERROR in ./node_modules/validator.js-asserts/dist/asserts/aba-routing-number-assert.js
Module not found: Error: Can't resolve 'abavalidator' in '/Users/scotth527/Desktop/UC Director Front end/UC-Director/UC-Director/node_modules/validator.js-asserts/dist/asserts'
 @ ./node_modules/validator.js-asserts/dist/asserts/aba-routing-number-assert.js 19:23-46
 @ ./node_modules/validator.js-asserts/dist/index.js
 @ ./node_modules/authy-client/dist/src/validator.js
 @ ./node_modules/authy-client/dist/src/client.js
 @ ./node_modules/authy-client/dist/src/index.js
 @ ./src/views/Pages/Login/Login.js
 @ ./src/App.js
 @ ./src/index.js
 @ multi ./src/index.js

ERROR in ./node_modules/validator.js-asserts/dist/asserts/big-number-less-than-or-equal-to-assert.js
Module not found: Error: Can't resolve 'bignumber.js' in '/Users/scotth527/Desktop/UC Director Front end/UC-Director/UC-Director/node_modules/validator.js-asserts/dist/asserts'
 @ ./node_modules/validator.js-asserts/dist/asserts/big-number-less-than-or-equal-to-assert.js 19:20-43
 @ ./node_modules/validator.js-asserts/dist/index.js
 @ ./node_modules/authy-client/dist/src/validator.js
 @ ./node_modules/authy-client/dist/src/client.js
 @ ./node_modules/authy-client/dist/src/index.js
 @ ./src/views/Pages/Login/Login.js
 @ ./src/App.js
 @ ./src/index.js
 @ multi ./src/index.js

ERROR in ./node_modules/validator.js-asserts/dist/asserts/big-number-less-than-assert.js
Module not found: Error: Can't resolve 'bignumber.js' in '/Users/scotth527/Desktop/UC Director Front end/UC-Director/UC-Director/node_modules/validator.js-asserts/dist/asserts'
 @ ./node_modules/validator.js-asserts/dist/asserts/big-number-less-than-assert.js 19:20-43
 @ ./node_modules/validator.js-asserts/dist/index.js
 @ ./node_modules/authy-client/dist/src/validator.js
 @ ./node_modules/authy-client/dist/src/client.js
 @ ./node_modules/authy-client/dist/src/index.js
 @ ./src/views/Pages/Login/Login.js
 @ ./src/App.js
 @ ./src/index.js
 @ multi ./src/index.js

ERROR in ./node_modules/validator.js-asserts/dist/asserts/big-number-greater-than-assert.js
Module not found: Error: Can't resolve 'bignumber.js' in '/Users/scotth527/Desktop/UC Director Front end/UC-Director/UC-Director/node_modules/validator.js-asserts/dist/asserts'
 @ ./node_modules/validator.js-asserts/dist/asserts/big-number-greater-than-assert.js 19:20-43
 @ ./node_modules/validator.js-asserts/dist/index.js
 @ ./node_modules/authy-client/dist/src/validator.js
 @ ./node_modules/authy-client/dist/src/client.js
 @ ./node_modules/authy-client/dist/src/index.js
 @ ./src/views/Pages/Login/Login.js
 @ ./src/App.js
 @ ./src/index.js
 @ multi ./src/index.js

ERROR in ./node_modules/validator.js-asserts/dist/asserts/big-number-greater-than-or-equal-to-assert.js
Module not found: Error: Can't resolve 'bignumber.js' in '/Users/scotth527/Desktop/UC Director Front end/UC-Director/UC-Director/node_modules/validator.js-asserts/dist/asserts'
 @ ./node_modules/validator.js-asserts/dist/asserts/big-number-greater-than-or-equal-to-assert.js 19:20-43
 @ ./node_modules/validator.js-asserts/dist/index.js
 @ ./node_modules/authy-client/dist/src/validator.js
 @ ./node_modules/authy-client/dist/src/client.js
 @ ./node_modules/authy-client/dist/src/index.js
 @ ./src/views/Pages/Login/Login.js
 @ ./src/App.js
 @ ./src/index.js
 @ multi ./src/index.js

ERROR in ./node_modules/validator.js-asserts/dist/asserts/big-number-equal-to-assert.js
Module not found: Error: Can't resolve 'bignumber.js' in '/Users/scotth527/Desktop/UC Director Front end/UC-Director/UC-Director/node_modules/validator.js-asserts/dist/asserts'
 @ ./node_modules/validator.js-asserts/dist/asserts/big-number-equal-to-assert.js 19:20-43
 @ ./node_modules/validator.js-asserts/dist/index.js
 @ ./node_modules/authy-client/dist/src/validator.js
 @ ./node_modules/authy-client/dist/src/client.js
 @ ./node_modules/authy-client/dist/src/index.js
 @ ./src/views/Pages/Login/Login.js
 @ ./src/App.js
 @ ./src/index.js
 @ multi ./src/index.js

ERROR in ./node_modules/validator.js-asserts/dist/asserts/big-number-assert.js
Module not found: Error: Can't resolve 'bignumber.js' in '/Users/scotth527/Desktop/UC Director Front end/UC-Director/UC-Director/node_modules/validator.js-asserts/dist/asserts'
 @ ./node_modules/validator.js-asserts/dist/asserts/big-number-assert.js 19:20-43
 @ ./node_modules/validator.js-asserts/dist/index.js
 @ ./node_modules/authy-client/dist/src/validator.js
 @ ./node_modules/authy-client/dist/src/client.js
 @ ./node_modules/authy-client/dist/src/index.js
 @ ./src/views/Pages/Login/Login.js
 @ ./src/App.js
 @ ./src/index.js
 @ multi ./src/index.js

ERROR in ./node_modules/validator.js-asserts/dist/asserts/credit-card-assert.js
Module not found: Error: Can't resolve 'creditcard' in '/Users/scotth527/Desktop/UC Director Front end/UC-Director/UC-Director/node_modules/validator.js-asserts/dist/asserts'
 @ ./node_modules/validator.js-asserts/dist/asserts/credit-card-assert.js 19:21-42
 @ ./node_modules/validator.js-asserts/dist/index.js
 @ ./node_modules/authy-client/dist/src/validator.js
 @ ./node_modules/authy-client/dist/src/client.js
 @ ./node_modules/authy-client/dist/src/index.js
 @ ./src/views/Pages/Login/Login.js
 @ ./src/App.js
 @ ./src/index.js
 @ multi ./src/index.js

ERROR in ./node_modules/validator.js-asserts/dist/asserts/international-bank-account-number-assert.js
Module not found: Error: Can't resolve 'iban' in '/Users/scotth527/Desktop/UC Director Front end/UC-Director/UC-Director/node_modules/validator.js-asserts/dist/asserts'
 @ ./node_modules/validator.js-asserts/dist/asserts/international-bank-account-number-assert.js 19:15-30
 @ ./node_modules/validator.js-asserts/dist/index.js
 @ ./node_modules/authy-client/dist/src/validator.js
 @ ./node_modules/authy-client/dist/src/client.js
 @ ./node_modules/authy-client/dist/src/index.js
 @ ./src/views/Pages/Login/Login.js
 @ ./src/App.js
 @ ./src/index.js
 @ multi ./src/index.js

ERROR in ./node_modules/validator.js-asserts/dist/asserts/iso-3166-country-assert.js
Module not found: Error: Can't resolve 'isoc' in '/Users/scotth527/Desktop/UC Director Front end/UC-Director/UC-Director/node_modules/validator.js-asserts/dist/asserts'
 @ ./node_modules/validator.js-asserts/dist/asserts/iso-3166-country-assert.js 25:20-35
 @ ./node_modules/validator.js-asserts/dist/index.js
 @ ./node_modules/authy-client/dist/src/validator.js
 @ ./node_modules/authy-client/dist/src/client.js
 @ ./node_modules/authy-client/dist/src/index.js
 @ ./src/views/Pages/Login/Login.js
 @ ./src/App.js
 @ ./src/index.js
 @ multi ./src/index.js

ERROR in ./node_modules/forever-agent/index.js
Module not found: Error: Can't resolve 'net' in '/Users/scotth527/Desktop/UC Director Front end/UC-Director/UC-Director/node_modules/forever-agent'
 @ ./node_modules/forever-agent/index.js 6:10-24
 @ ./node_modules/request/request.js
 @ ./node_modules/request/index.js
 @ ./node_modules/authy-client/dist/src/logging/request.js
 @ ./node_modules/authy-client/dist/src/index.js
 @ ./src/views/Pages/Login/Login.js
 @ ./src/App.js
 @ ./src/index.js
 @ multi ./src/index.js

ERROR in ./node_modules/tough-cookie/lib/cookie.js
Module not found: Error: Can't resolve 'net' in '/Users/scotth527/Desktop/UC Director Front end/UC-Director/UC-Director/node_modules/tough-cookie/lib'
 @ ./node_modules/tough-cookie/lib/cookie.js 32:10-24
 @ ./node_modules/request/lib/cookies.js
 @ ./node_modules/request/index.js
 @ ./node_modules/authy-client/dist/src/logging/request.js
 @ ./node_modules/authy-client/dist/src/index.js
 @ ./src/views/Pages/Login/Login.js
 @ ./src/App.js
 @ ./src/index.js
 @ multi ./src/index.js

ERROR in ./node_modules/tunnel-agent/index.js
Module not found: Error: Can't resolve 'net' in '/Users/scotth527/Desktop/UC Director Front end/UC-Director/UC-Director/node_modules/tunnel-agent'
 @ ./node_modules/tunnel-agent/index.js 3:10-24
 @ ./node_modules/request/lib/tunnel.js
 @ ./node_modules/request/request.js
 @ ./node_modules/request/index.js
 @ ./node_modules/authy-client/dist/src/logging/request.js
 @ ./node_modules/authy-client/dist/src/index.js
 @ ./src/views/Pages/Login/Login.js
 @ ./src/App.js
 @ ./src/index.js
 @ multi ./src/index.js

ERROR in ./node_modules/validator.js-asserts/dist/asserts/ip-assert.js
Module not found: Error: Can't resolve 'net' in '/Users/scotth527/Desktop/UC Director Front end/UC-Director/UC-Director/node_modules/validator.js-asserts/dist/asserts'
 @ ./node_modules/validator.js-asserts/dist/asserts/ip-assert.js 8:11-25
 @ ./node_modules/validator.js-asserts/dist/index.js
 @ ./node_modules/authy-client/dist/src/validator.js
 @ ./node_modules/authy-client/dist/src/client.js
 @ ./node_modules/authy-client/dist/src/index.js
 @ ./src/views/Pages/Login/Login.js
 @ ./src/App.js
 @ ./src/index.js
 @ multi ./src/index.js

ERROR in ./node_modules/validator.js-asserts/dist/asserts/taxpayer-identification-number-assert.js
Module not found: Error: Can't resolve 'tin-validator' in '/Users/scotth527/Desktop/UC Director Front end/UC-Director/UC-Director/node_modules/validator.js-asserts/dist/asserts'
 @ ./node_modules/validator.js-asserts/dist/asserts/taxpayer-identification-number-assert.js 16:14-38
 @ ./node_modules/validator.js-asserts/dist/index.js
 @ ./node_modules/authy-client/dist/src/validator.js
 @ ./node_modules/authy-client/dist/src/client.js
 @ ./node_modules/authy-client/dist/src/index.js
 @ ./src/views/Pages/Login/Login.js
 @ ./src/App.js
 @ ./src/index.js
 @ multi ./src/index.js

ERROR in ./node_modules/forever-agent/index.js
Module not found: Error: Can't resolve 'tls' in '/Users/scotth527/Desktop/UC Director Front end/UC-Director/UC-Director/node_modules/forever-agent'
 @ ./node_modules/forever-agent/index.js 7:10-24
 @ ./node_modules/request/request.js
 @ ./node_modules/request/index.js
 @ ./node_modules/authy-client/dist/src/logging/request.js
 @ ./node_modules/authy-client/dist/src/index.js
 @ ./src/views/Pages/Login/Login.js
 @ ./src/App.js
 @ ./src/index.js
 @ multi ./src/index.js

ERROR in ./node_modules/tunnel-agent/index.js
Module not found: Error: Can't resolve 'tls' in '/Users/scotth527/Desktop/UC Director Front end/UC-Director/UC-Director/node_modules/tunnel-agent'
 @ ./node_modules/tunnel-agent/index.js 4:10-24
 @ ./node_modules/request/lib/tunnel.js
 @ ./node_modules/request/request.js
 @ ./node_modules/request/index.js
 @ ./node_modules/authy-client/dist/src/logging/request.js
 @ ./node_modules/authy-client/dist/src/index.js
 @ ./src/views/Pages/Login/Login.js
 @ ./src/App.js
 @ ./src/index.js
 @ multi ./src/index.js

ERROR in ./node_modules/validator.js-asserts/dist/asserts/uk-modulus-checking-assert.js
Module not found: Error: Can't resolve 'uk-modulus-checking' in '/Users/scotth527/Desktop/UC Director Front end/UC-Director/UC-Director/node_modules/validator.js-asserts/dist/asserts'
 @ ./node_modules/validator.js-asserts/dist/asserts/uk-modulus-checking-assert.js 21:28-58
 @ ./node_modules/validator.js-asserts/dist/index.js
 @ ./node_modules/authy-client/dist/src/validator.js
 @ ./node_modules/authy-client/dist/src/client.js
 @ ./node_modules/authy-client/dist/src/index.js
 @ ./src/views/Pages/Login/Login.js
 @ ./src/App.js
 @ ./src/index.js
 @ multi ./src/index.js

**Comment by ruimarinho** [comment]
Not sure what this is about. @pgom do you have any idea?

**Comment by ruimarinho** [comment]
@scottyh527 while I don't know how to best address this issue, my hunch is that web pack is trying to parse dynamic imports (i.e. a `require` which is dynamically called inside a function). The goal on that particular validation lib was to not require all modules to be dependencies. 

Is there a way you can whitelist certain file paths from webpack's bundling?

**Comment by ruimarinho** [comment]
Closing the issue but the discussion may continue.

**Comment by pgom** [comment]
@scottyh527 you can probably fix it by excluding this module from the `babel-loader` definition on your webpack configuration
